batch_size: 8
accumulate_grad_batches: 4
epochs: 100
logs_dir: /walnet/logs        # where all checkpoints, logs are stored
ckpt_dir: /walnet/checkpoints
num_gpus: 1           # number of GPUs to use
num_workers: 8        # number of workers for dataloader
save_top_k: 1         # Save top k checkpoints
pin_memory: true
distributed: false
